#!/bin/bash
opkg remove dsl-vrx200-firmware-xdsl-a dsl-vrx200-firmware-xdsl-a-patch \
dsl-vrx200-firmware-xdsl-b dsl-vrx200-firmware-xdsl-b-patch \
kmod-ltq-vdsl-vr9  ltq-vdsl-app ltq-vdsl-mei_test \
ltq-vdsl-vr9-vectoring-fw-installer atm-esi kmod-atm kmod-ltq-atm-vr9 \
kmod-ltq-ptm-vr9 linux-atm br2684ctl kmod-pppoa ppp-mod-pppoa kmod-atmtcp \
atm-diagnostics kmod-ltq-vdsl-vr9-mei --force-depends
sed -i 's|pppoe-wan|eth0.2|g' /etc/lcd4linux.conf
sed -i 's|pppoe-wan|eth0.2|g' /etc/lcd4linux.conf.black
sed -i 's|pppoe-wan|eth0.2|g' /etc/lcd4linux.conf.white
sed -i 's|pppoe-wan|eth0.2|g' /etc/speed
echo
echo .........................................................................
echo Zrobione!
echo Wszystkie moduły ADSL/VDSL zostały usuniete. Zrestartuj router!
echo .........................................................................
echo Done!
echo All ADSL/VDSL modules has been removed. Restart the router!
echo .........................................................................
exit 0
