#!/bin/bash
uci set wireless.wl000.disabled='1'
uci set wireless.default_wl000.disabled='1'
#uci set wireless.wl010.disabled='1'
#uci set wireless.default_wl010.disabled='1'
uci commit wireless
wifi down && ifup wan
echo
echo ............................................
echo WiFi 5 GHz jest nieaktywne.
echo ............................................
exit 0

