#!/bin/bash
uci set wireless.wl010.disabled='0'
uci set wireless.default_wl010.disabled='0'
#uci set wireless.wl010.disabled='0'
#uci set wireless.default_wl010.disabled='0'
uci commit wireless
wifi up
echo
echo .......................................... 
echo WiFi 2 GHz jest aktywne.
echo .......................................... 
exit 0

