#!/bin/bash
uci set wireless.wl000.disabled='1'
uci set wireless.default_wl000.disabled='1'
uci set wireless.wl010.disabled='1'
uci set wireless.default_wl010.disabled='1'
uci commit wireless
wifi down
echo
echo ............................................
echo WiFi 2.4 GHz oraz 5 GHz są nieaktywne.
echo ............................................
echo 2.4 GHz and 5GHz WiFi networks are disabled.
echo ............................................
exit 0

